version: '3.5'

services:
  newmips:
    depends_on:
      - database
    image: newmips/newmips:latest
    networks:
      proxy:
        ipv4_address: 172.21.0.14
    ports:
      - "1337:1337"
      - "9001-9100:9001-9100"
    environment:
      SERVER_IP: "172.21.0.14"
      DATABASE_IP: "172.21.0.15"
      NPS_ENV: "docker"
  database:
    image: newmips/newmips-mysql:latest
    networks:
      proxy:
        ipv4_address: 172.21.0.15
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd+
      MYSQL_DATABASE: newmips
      MYSQL_USER: newmips
      MYSQL_PASSWORD: newmips

networks:
  proxy:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

volumes:
  db_data: {}
