const mandatoryInstructions = [
	"create module home",
	"create module Administration",
	"create entity User",
	"add field login",
	"set field login required",
	"add field password",
	"add field email with type email",
	"add field token_password_reset",
	"add field enabled with type checkbox",
	"create entity Role",
	"add field label",
	"set field label required",
	"create entity Group",
	"add field label",
	"set field label required",
	"select entity User",
	"add field Role related to many Role using label",
	"add field Group related to many Group using label",
	"set field Role required",
	"set field Group required",
	"entity Role has many User",
	"entity Group has many User",
	"add entity API credentials",
	"add field Client Name",
	"add field Client Key",
	"add field Client Secret",
	"add field Token",
	"add field Token timeout TMSP",
	"add field role related to many Role using label",
	"add field group related to many Group using label",
	"add entity Synchronization",
	"add field Journal backup file",
	"entity Synchronization has one API credentials",
	"add entity Synchro credentials",
	"add field Cloud host with type url",
	"add field Client key",
	"add field Client secret",
	"add widget stat on entity User",
	"add entity Status",
	"add field Entity",
	"add field Field",
	"add field Name",
	"add field Color with type color",
	"add field Accepted group related to many Group using Label",
	"add field Button label",
	"add field Position with type number",
	"add field Default with type boolean",
	"add field Comment with type boolean",
	"entity Status has many Status called Children",
	"entity Status has many Translation called Translations",
	"select entity translation",
	"add field Language",
	"add field Value",
	"create entity Media",
	"add field Type with type enum and values Mail, Notification, SMS, Task",
	"add field Name",
	"set field Name required",
	"add field Target entity",
	"entity status has many Action called Actions",
	"select entity action",
	"add field Media related to Media using name",
	"add field Order with type number",
	"add field Execution with type enum and values Immédiate, Différée with default value Immédiate",
	"create entity Robot",
	"add field Current status with type enum and values CONNECTED, DISCONNECTED, WORKING",
	"add field Name",
	"add field Api credentials related to api credentials using client name",
	"add field Comment with type regular text",
	"create entity Task",
	"add component status with name State",
	"add field Title",
	"set field Title required",
	"add field Type with type enum and values Manual, Automatic and default value Manual",
	"add field Planned date with type date",
	"add field Execution start date with type date",
	"add field Execution finish date with type date",
	"add field Duration with type decimal",
	"add field Data flow with type regular text",
	"add field Robot related to Robot using Name",
	"add field Procedure with type regular text",
	"add component file storage with name Documents",
	"entity Media has one Media Mail",
	"entity Media has one Media Notification",
	"entity Media has one Media SMS",
	"entity Media has one Media Task",
	"entity Task has many Execution",
	"select entity Execution",
	"add field Execution start date with type datetime",
	"add field Execution end date with type datetime",
	"add field State with type enum and values SUCCESS, ERROR",
	"add field Error cause",
	"add field Logs with type file",
	"add field Execution finish date with type datetime",
	"add entity Process",
	"add field Name",
	"add entity Program",
	"add field Name",
	"add field Description with type text",
	"add field Program file with type file",
	"entity Program has many Page",
	"select entity Page",
	"add field Title",
	"add field URL with type url",
	"add field Script with type regular text",
	"add field Delay with type number",
	"add field Timeout with type number",
	"add field startwith url with type url",
	"add field startwith_method with type enum and values GET, POST, HEAD, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH",
	"add field endwith url with type url",
	"add field endwith_method with type enum and values GET, POST, HEAD, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH",
	"add field Execute on error with type boolean",
	"add field Type with type enum and values Script, Séquence with default value Script",
	"add field Order with type number",
	"add field download_url with type url",
	"add field download_filename",
	"select entity Process",
	"add field Program related to Program using name",
	"select entity task",
	"add field Process related to Process using name",
	"select entity media task",
	"add field Task name",
	"add field Task type with type enum and values Manual, Automatic and default value Manual",
	"add field Assignment logic",
	"add field Data flow with type text",
	"add field Process related to Process using name",
	"select entity media mail",
	"add field To",
	"add field Cc",
	"add field Cci",
	"add field From",
	"add field Attachments",
	"add field Subject",
	"add field Content with type text",
	"select entity media notification",
	"add field Title",
	"add field Description",
	"add field Icon",
	"add field Color with type color",
	"add field targets",
	"add entity Notification",
	"add field Title",
	"add field Description",
	"add field URL",
	"add field Color with type color",
	"add field Icon",
	"select entity media SMS",
	"add field Message with type regular text",
	"add field Phone numbers",
	"add entity Inline Help",
	"add field Entity",
	"add field Field",
	"add field Content with type text",
	"entity user has many notification",
	"entity notification has many user",
	"add param entity User Guide",
	"add field File with type file",
	"select module Administration",
	"add entity document template",
	"add field Name",
	"set field Name required",
	"add field File with type file",
	"set field File required",
	"add field Entity",
	"set field Entity required",
	"add field Format pair",
	"set field Format pair required",
	"add field Group related to many group using label",
	"add field Role related to many role using label",
	"add entity Image ressources",
	"add field Image with type image",
	"set field Image required",
	"add field code",
	"set field code required",
	"select module home"
];

module.exports = mandatoryInstructions;