-- CREATE NEWMIPS DATABASE FOR MySQL

DROP DATABASE IF EXISTS newmips;
CREATE DATABASE newmips
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'newmips'@'127.0.0.1' IDENTIFIED BY 'newmips';
CREATE USER IF NOT EXISTS 'newmips'@'%' IDENTIFIED BY 'newmips';
GRANT ALL PRIVILEGES ON *.* TO 'newmips'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'newmips'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;